# Generated by Django 4.2.7 on 2025-07-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
