# Generated by Django 4.2.7 on 2025-08-27 19:51

from django.db import migrations, models
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
                ("response", models.JSONField()),
                ("hits", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("question", models.TextField()),
                (
                    "question_embedding",
                    pgvector.django.vector.VectorField(dimensions=768, null=True),
                ),
                ("generated_sql", models.TextField(blank=True, null=True)),
                ("sql_result", models.JSONField(blank=True, null=True)),
                (
                    "model_name",
                    models.CharField(default="gemini-embedding-001", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SchemaEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_name", models.CharField(max_length=255)),
                ("definition", models.TextField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
            ],
        ),
    ]
